# Generated by Django 5.2.10 on 2026-02-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
