# Generated by Django 5.2.13 on 2026-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_tasks_done_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="Done",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Done",
        ),
    ]
