# Generated by Django 5.2.13 on 2026-05-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_tasks_done_delete_done"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="Done",
            new_name="done",
        ),
    ]
