# Generated by Django 5.2.13 on 2026-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_done_tasks_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
